mom_style_api/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from store_admin_app.views import IndexView


urlpatterns = [
	path('admin/', admin.site.urls),
	url(r'^store/', include('store_app.urls', namespace='store-app-namespace')),
	url(r'^store-admin/', include('store_admin_app.urls', namespace='store-admin-app-namespace')),
	url(r'^$', IndexView, name='website'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store_admin_app/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from .views import *

app_name = 'store_admin_app'

urlpatterns = [
	url(r'^index/$',IndexView ,name='index-view'),
	url(r'^login/$',LoginView ,name='login-view'),
	url(r'^logout/$',LogoutView ,name='logout-view'),
	url(r'^categories/$',CategoriesView ,name='categories-view'),
	url(r'^collections/$',CollectionsView ,name='collections-view'),
	url(r'^coupons/$',CuponsListView ,name='coupon-view'),
	url(r'^orders/$',OrdersView ,name='orders-view'),
	url(r'^products/$',ProductsView ,name='products-view'),
	url(r'^custom-colors/$',CustomColorsView ,name='custom-colors-view'),
	url(r'^category/create/$',CreateCategoryView ,name='category-create-view'),
	url(r'^collection/create/$',CreateCollectionView ,name='collection-create-view'),
	url(r'^product/create/$',CreateProductView ,name='product-create-view'),
	url(r'^coupon/create/$',CuponsCreatelView ,name='coupon-create-view'),
	url(r'^custom-colors/create/$',CreateCustomColorsView ,name='custom-colors-create-view'),
	url(r'^category/crud/(?P<id>[0-9]+)/$',CategoryCRUDView ,name='category-crud-view'),
	url(r'^collection/crud/(?P<id>[0-9]+)/$',CollectionCRUDView ,name='collection-crud-view'),
	url(r'^coupon/crud/(?P<id>[0-9]+)/$',CuponCRUDView ,name='coupon-crud-view'),
	url(r'^order/(?P<id>[0-9]+)/$',OrderDetailView ,name='order-detail-view'),
	url(r'^product/crud/(?P<id>[0-9]+)/$',ProductCRUDView ,name='product-crud-view'),
	url(r'^custom-colors/crud/(?P<id>[0-9]+)/$',CustomColorsCRUDView ,name='custom-colors-crud-view'),
]

store_app/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from .views import *

app_name = 'store_app'

urlpatterns = [
	url(r'^categories/$',CategoryListView.as_view(),name='category-list-view'),
	url(r'^categories/men/$',CategoryMenListView.as_view(),name='category-list-men-view'),
	url(r'^categories/women/$',CategoryWomenListView.as_view(),name='category-list-women-view'),
	url(r'^collections/$',CustomCollectionListView.as_view(),name='collection-list-view'),
	url(r'^collections/men/$',CustomCollectionMenListView.as_view(),name='collection-list-men-view'),
	url(r'^collections/women/$',CustomCollectionWomenListView.as_view(),name='collection-list-woman-view'),
	url(r'^category/title/(?P<title>[\w\-]+)/$',CategoryTitleDetailView.as_view(),name='category-title-view'),
	url(r'^category/title/men/(?P<title>[\w\-]+)/$',CategoryTitleMenDetailView.as_view(),name='category-title-view'),
	url(r'^category/title/women/(?P<title>[\w\-]+)/$',CategoryTitleWomenDetailView.as_view(),name='category-title-view'),
	url(r'^collection/title/(?P<title>[\w\-]+)/$',CustomCollectionTitleDetailView.as_view(),name='collection-title-view'),
	url(r'^products-extra-tags/$',ProductsPerExtraTag.as_view(),name='products-extra-tags-list-view'),
	url(r'^collections/(?P<id>[0-9]+)/$',CustomCollectionDetailView.as_view(),name='collection-list-view'),
	url(r'^product-images/(?P<id>[0-9]+)/$', ProductImagesView.as_view(), name='product-images-detail-api'),
	url(r'^categories/(?P<id>[0-9]+)/$', CategoryDetailView.as_view(), name='category-detail-api'),
	url(r'^products/$',ProductListView.as_view(),name='products-list-view'),
	url(r'^products/(?P<id>[0-9]+)/$', ProductDetailView.as_view(), name='products-detail-api'),
	url(r'^cart/(?P<token>[0-9A-Za-z_\-]+)/$',CartView.as_view(),name='cart-detail-view'),
	url(r'^cart/$',CartView.as_view(),name='cart-view'),
	url(r'^cart/delete-product/(?P<id>[0-9]+)/$', ProductVariationView.as_view(), name='delete-product-api'),
	url(r'^custom-products/$',ProductVariationListView.as_view(),name='custom-products-list-view'),
	url(r'^custom-products/(?P<id>[0-9]+)/$', ProductVariationView.as_view(), name='custom-products-detail-api'),
	url(r'^order/(?P<cart_token>[0-9A-Za-z_\-]+)/$', CheckoutView.as_view(), name='checkout-detail-api'),
	url(r'^shipping-info/(?P<cart_token>[0-9A-Za-z_\-]+)/$', ShippingInfoView.as_view(), name='checkout-detail-api'),
	url(r'^checkout-paypal/(?P<cart_token>[0-9A-Za-z_\-]+)/$', OderCheckoutPaypalView.as_view(), name='checkout-detail-api'),
	url(r'^coupon/(?P<token>[0-9A-Za-z_\-]+)/$', AddCoupon.as_view(), name='coupon-add-api'),
]

store_admin_app/models.py
from django.db import models

# Create your models here.

store_admin_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.conf import settings
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.core.mail import EmailMultiAlternatives
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q

import json
from datetime import datetime
from random import randint

from rest_framework.response import Response
from rest_framework import status
from rest_framework.generics import *
from rest_framework.views import APIView

from .models import *
from .serializers import *

import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

from store_app.models import *

def IndexView(request):
	if request.user is None or request.user.is_authenticated == False:
		return redirect('/store-admin/login/')

	top_amount = min(len(Product.objects.all()),10)
	top_ten = Product.objects.all().order_by('-amount_sold')[:2]

	top_products = Product.objects.all().order_by('-amount_sold')
	return render(request, "store_admin_app/index.html",{'top_ten_products': top_ten, "top_products": top_products})

#=============================================================================

def LoginView(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect('/store-admin/index/')
	elif request.method == 'GET':
		if request.user is not None and request.user.is_authenticated == True:
			return HttpResponseRedirect('/store-admin/index/')
		else:
			return render(request, "store_admin_app/login.html",{})
	return render(request, "store_admin_app/login.html",{})

#=============================================================================

def LogoutView(request):
	logout(request)
	return HttpResponseRedirect('/store-admin/index/')

#=============================================================================

def CategoriesView(request):
	if request.user is None or request.user.is_authenticated == False:
		return redirect('/store-admin/login/')

	if request.method == "GET":
		categories = Category.objects.all()
		return render(request, "store_admin_app/categories.html",{"categories":categories})

	elif request.method == 'POST':
		query = request.POST['search_category']
		categories = Category.objects.filter(title__icontains=query)
		return render(request, "store_admin_app/categories.html",{"categories":categories})

#=============================================================================

def CollectionsView(request):
	if request.user is None or request.user.is_authenticated == False:
		return redirect('/store-admin/login/')

	if request.method == "GET":
		collections = CustomCollection.objects.all()
		return render(request, "store_admin_app/collections.html",{"collections":collections})

	elif request.method == 'POST':
		query = request.POST['search_collection']
		collections = CustomCollection.objects.filter(title__icontains=query)
		return render(request, "store_admin_app/collections.html",{"collections":collections})


#=============================================================================

def ProductsView(request):
	if request.user is None or request.user.is_authenticated == False:
		return redirect('/store-admin/login/')

	if request.method == "GET":
		collections = CustomCollection.objects.all()
		products = Product.objects.all()
		return render(request, "store_admin_app/products.html",{"products":products,"collections":collections, "default_collection":"All"})

	elif request.method == 'POST':
		collections = CustomCollection.objects.all()

		if 'search_product' in request.POST:
			default_collection = "All"
			query = request.POST['search_product']
			products = Product.objects.filter(title__icontains=query)
		else:
			query = request.POST['filter_collection']
			if query == 'All':
				default_collection = "All"
				products = Product.objects.all()
			else:
				default_collection = query
				products = Product.objects.filter(collection__title=query)

		return render(request, "store_admin_app/products.html",{"products":products,"collections":collections, "default_collection": default_collection})


#=============================================================================

def OrdersView(request):
	if request.user is None or request.user.is_authenticated == False:
		return redirect('/store-admin/login/')

	status_map = {"Ordered": "Pedido por cliente", "OrderedMex": "Pedido a Mexico",
				  "ProdMex": "Produciendose en Mexico",
				  "ToUSA": "Camino a USA", "ToUPS": "En USA Listo para UPS", "UPS": "UPS: Camino a cliente",
				  "Received": "Recibido por cliente", "Canceled": "Cancelada", "Refund": "Refund"}

	if request.method == "GET":

		orders = Order.objects.all().filter(payment__isnull=False)
		return render(request, "store_admin_app/orders.html",{"orders":orders, "status_map": status_map, "default_order_status": "All"})

	elif request.method == 'POST':
		if 'search_order' in request.POST:
			default_order_status = "All"
			query = request.POST['search_order']
			orders = Order.objects.filter(Q(user_first_name__icontains=query) | Q(user_last_name__icontains=query) | Q(email__icontains=query)).filter(payment__isnull=False)
		else:
			query = request.POST['filter_order_status']
			default_order_status = query
			if query == 'All':
				orders = Order.objects.all().filter(payment__isnull=False)
			else:
				orders = Order.objects.filter(status=query).filter(payment__isnull=False)
		return render(request, "store_admin_app/orders.html",{"orders":orders, "status_map": status_map, "default_order_status": default_order_status})




def CustomColorsView(request):
	if request.user is None or request.user.is_authenticated == False:
		return redirect('/store-admin/login/')

	if request.method == "GET":
		available_colors = CustomColor.objects.all()
		return render(request, "store_admin_app/available_colors.html",{"available_colors":available_colors})

	elif request.method == 'POST':
		query = request.POST['search_available_colors']
		available_colors = CustomColor.objects.filter(title__icontains=query)
		return render(request, "store_admin_app/available_colors.html",{"available_colors":available_colors})











#=============================================================================

def OrderDetailView(request, id):
	if request.user is None or request.user.is_authenticated == False:
		return redirect('/store-admin/login/')

	if request.method == "GET":
		order = Order.objects.get(id=id)
		payment = Payment.objects.get(id = order.payment.id)

		status_map = {"Ordered": "Pedido por cliente", "OrderedMex": "Pedido a Mexico",
					  "ProdMex": "Produciendose en Mexico",
					  "ToUSA": "Camino a USA", "ToUPS": "En USA Listo para UPS", "UPS": "UPS: Camino a cliente",
					  "Received": "Recibido por cliente", "Canceled": "Cancelada", "Refund": "Refund"}

		products = order.cart.product_variation_set.all()

		return render(request, "store_admin_app/order_detail.html",{"order": order, "status_map": status_map, "payment": payment, "cart": order.cart, "products": products})

	if request.method == "POST":

		order = Order.objects.get(id=id)
		payment = Payment.objects.get(id=order.payment.id)

		products = order.cart.product_variation_set.all()

		status_map = {"Ordered": "Pedido por cliente", "OrderedMex": "Pedido a Mexico", "ProdMex": "Produciendose en Mexico",
					  "ToUSA": "Camino a USA", "ToUPS": "En USA Listo para UPS", "UPS": "UPS: Camino a cliente",
					  "Received": "Recibido por cliente", "Canceled": "Cancelada", "Refund": "Refund"}

		if 'save' in request.POST:
			order_status = request.POST['order_status']
			order.status = order_status
			order.save()


		elif 'refund' in request.POST:
			client_id = payment.stripe_charge_id

			try:
				result_refund = stripe.Refund.create(
					charge=client_id,
				)

				if(result_refund.status == "succeeded"):
					payment.refund = "Refund successfully made"
				else:
					payment.refund = "Error"
				payment.save()
			except:
				payment.refund = "Error"
				payment.save()

		return render(request, "store_admin_app/order_detail.html", {"order": order, "status_map": status_map, "payment": payment, "cart": order.cart, "products": products})

















#=============================================================================

def CreateCategoryView(request):
	if request.user is None or request.user.is_authenticated == False:
		return redirect('/store-admin/login/')

	if request.method == "GET":
		return render(request, "store_admin_app/category_create.html",{"message": "No Error"})

	elif request.method == 'POST':
		try:
			title = request.POST['title']
			if title.isspace() or (not title):
				return render(request, "store_admin_app/category_create.html",
							  {"message": "Introduzca el titulo de la categoria"})
			else:
				if 'image' in request.FILES:
					image = request.FILES['image']
					Category.objects.create(title=title, image = image)
					return redirect('/store-admin/categories/')
				else:
					return render(request, "store_admin_app/category_create.html",{"message": "Introduzca la foto de la categoria"})
		except:
			return render(request, "store_admin_app/category_create.html",{"message": "Error"})



#=============================================================================

def CreateCollectionView(request):
	if request.user is None or request.user.is_authenticated == False:
		return redirect('/store-admin/login/')

templates/store_admin_app/available_colors.html
{% extends "store_admin_app/base.html" %}
{% load static %}

{% block content %}


<div class = 'custom-colors-div'>

 <link rel="stylesheet" type='text/css' href="{% static 'store_admin_app/css/available_colors.css'%}?{% now 'U' %}">

     <h1>
        Colores Personalizados
    </h1>


<div class = 'search-form-div'>
 <form method="post">

       {% csrf_token %}

      <div class="input-group mb-3">
        <input  name="search_available_colors" type="text" class="form-control" placeholder="Buscar color por titulo ... "/>
        <button type="submit" class="btn btn-primary search-button">
          Buscar
        </button>
      </div>
 </form>


<div class="create-button-div">
<a href='{% url "store_admin_app:custom-colors-create-view" %}'>
   <button class="btn btn-primary create-button">
     ADICIONAR +
   </button>
   </a>
    </div>


 </div>

     <div class="custom-colors-list-div">
        <h2>Lista de Colores Personalizados </h2>
                 <div class="custom-colors-list-elements-div">
                      {% for available_color in available_colors %}
                    <div class='custom-colors-list'>
                            <a class='custom-colors-list-link' href="{% url 'store_admin_app:custom-colors-crud-view' id=available_color.id %}">
                                    <div style="height:40px; width:40px; background-color:{{available_color.code}}; border: 3px solid lightsteelblue" class="custom-colors-pre-div"></div>
                                <div class="custom-colors-nickname-div">
                                    <p class='custom-colors-list-element'>
                                  {{ available_color.title }} - {{available_color.code}}
                              </p>
                            </div>
                      </a>
                    </div>

            {% endfor %}
         </div>
     </div>


 </div>

{% endblock content %}

templates/store_admin_app/available_colors_crud.html
{% extends "store_admin_app/base.html" %}
{% load static %}

{% block content %}

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>


 <link rel="stylesheet" type='text/css' href="{% static 'store_admin_app/css/available_colors_crud.css'%}?{% now 'U' %}">

<div class='custom-colors-div'>

    <h1>
        Editar Color Personalizado
  </h1>



   {% if message != "No Error" %}

  <div class="alert alert-danger d-flex align-items-center" role="alert">
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
      <div>
       {{message}}
      </div>
  </div>
  {% endif %}



  <form method="post" class='custom-colors-form' enctype = "multipart/form-data" >

    {% csrf_token %}

     <div class="mb-3 form-field-div">
      <label for="title" class="form-label form-field-label">Titulo del Color Personalizado</label>
      <input type="text" value="{{custom_color.title}}" name="title" class="form-control" id="title">
    </div>


      <div class="mb-3 form-field-div">
           <label for="code" class="form-label form-field-label">Code
            <input type="color" class="form-control form-control-color" value="{{custom_color.code}}" name="code"  id="code" onchange="myFunction();" />
            </label>
           <span id="custom-colors-p"></span>
    </div>


 <div class="row">
      <div class='delete-button-div col-sm-6'>
      <button type="submit" class="btn btn-danger delete-button" name="delete" value="delete">Borrar</button>
    </div>

    <div class='save-button-div col-sm-6'>
      <button type="submit" class="btn btn-primary save-button" name="save" value="save">Guardar Cambios</button>
    </div>
    </div>

  </form>
</div>




<script>
    function myFunction(){
        var x = document.getElementById("custom-colors-p");
        var code = document.getElementById("code");
        x.innerHTML = code.value;
        console.log(code);
    }
</script>


{% endblock content %}

templates/store_admin_app/base.html
    {% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Admin Panel</title>
    </head>

    <link rel="stylesheet" type='text/css' href="{% static 'store_admin_app/css/bootstrap/bootstrap.min.css' %}">
	<link rel="stylesheet" type='text/css' href="{% static 'store_admin_app/css/bootstrap/bootstrap.css' %}">

	<link rel="stylesheet" type='text/css' href="{% static 'store_admin_app/css/base.css' %}">

    <script src="{% static   'store_admin_app/js/bootstrap/bootstrap.min.js' %}"></script>

    <body>

      <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'store_admin_app:index-view'%}">Panel de Administracion</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store_admin_app:categories-view' %}">Categorias</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'store_admin_app:collections-view' %}">Colecciones</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'store_admin_app:custom-colors-view' %}">Colores Personalizados</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store_admin_app:products-view' %}">Productos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store_admin_app:orders-view' %}">Ordenes</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'store_admin_app:coupon-view' %}">Cupones</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store_admin_app:logout-view' %}">Salir de la Cuenta</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}{% endblock content %}
    </body>
</html>

templates/store_admin_app/collections.html
{% extends "store_admin_app/base.html" %}
{% load static %}

{% block content %}


<div class = 'collection-div'>


 <link rel="stylesheet" type='text/css' href="{% static 'store_admin_app/css/collections.css'%}?{% now 'U' %}">


    <h1>
        Colecciones
    </h1>

    <div class = 'search-form-div'>
 <form method="post">
       {% csrf_token %}
      <div class="input-group mb-3">
        <input  name="search_collection" type="text" class="form-control" placeholder="Buscar por titulo ... "/>
        <button type="submit" class="btn btn-primary search-button">
          Buscar
        </button>
      </div>
 </form>

<div class="create-button-div">
    <a href='{% url "store_admin_app:collection-create-view" %}'>
       <button class="btn btn-primary create-button">
         ADICIONAR +
       </button>
       </a>
</div>

 </div>

    <div class="collection-list-div">
        <h2>Lista de Colecciones </h2>
        <div class="collection-list-elements-div">
          {% for coll in collections %}
        <div class='collection-list'>
                <a class='collection-list-link' href="{% url 'store_admin_app:collection-crud-view' id=coll.id %}">
              <p class='collection-list-element'>{{ coll }}</p>
          </a>
        </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

templates/store_admin_app/login.html
{% extends "store_admin_app/base.html" %}
{% load static %}

{% block content %}

 <link rel="stylesheet" type='text/css' href="{% static 'store_admin_app/css/login.css'%}?{% now 'U' %}">

<div class='login-div'>


  <div class="'header-div">
      <h1>
        Login/Accede a tu cuenta de Admin
      </h1>
  </div>


  <form method="post" class='login-form'>

    {% csrf_token %}

    <div class="mb-3 form-field-div">
      <label for="username" class="form-label"><p class="form-p">Username</p></label>
      <input type="text" name="username" class="form-control" id="username">
    </div>
    <div class="mb-3 form-field-div">
      <label for="password" class="form-label"><p class="form-p">Password</p></label>
      <input type="password" name="password" class="form-control" id="password">
    </div>
    <div class='login-button-div'>
    <button type="submit" class="btn btn-primary login-button">Login</button>
    </div>

  </form>

</div>


{% endblock content %}

templates/store_admin_app/orders.html
{% extends "store_admin_app/base.html" %}
{% load static %}
{% load custom_tags %}

{% block content %}


<div class = 'order-div'>

 <link rel="stylesheet" type='text/css' href="{% static 'store_admin_app/css/orders.css'%}?{% now 'U' %}">


    <h1>
        Ordenes
    </h1>


<div class = 'search-form-div'>

    <form method="post">
       {% csrf_token %}
      <div class="input-group mb-3">
        <input  name="search_order" type="text" class="form-control" placeholder="Buscar por nomber/apellido/email ... "/>
        <button type="submit" class="btn btn-primary search-button">
          Buscar
        </button>
      </div>
 </form>
    </div>

    <div class = 'filter-status-form-div'>

    <form method="post">
       {% csrf_token %}
      <div class="input-group mb-3">
        <label for="filter_order_status" class="form-label">Estatus de la Orden</label>
              <select class="form-select" name="filter_order_status" id="filter_order_status" value="filter_order_status" onchange="submit();">
                  {% if default_order_status == "All" %}
                    <option value="All" selected>All</option>
                  {% else %}
                     <option value="All">All</option>
                  {% endif %}
                  {% for key, val  in status_map.items %}
                      {% if default_order_status == key %}
                         <option value="{{key}}" selected>{{val}}</option>
                      {% else %}
                          <option value="{{key}}">{{val}}</option>
                      {% endif %}
                {% endfor %}
              </select>
      </div>
 </form>



 </div>

  <div class="order-list-div">
        <h2>Lista de Ordenes </h2>
            <div class="order-list-elements-div">
              {% for order in orders %}
                <div class='order-list'>
                        <a class='order-list-link' href="{% url 'store_admin_app:order-detail-view' id=order.id %}">
                      <p class='order-list-element'>{{ order }} - {{status_map | keyvalue:order.status}}</p>
                  </a>
                </div>
             {% endfor %}
            </div>
         </div>


 </div>

{% endblock content %}